### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/acm-atlas#10]
- Implement FAQ section with dropdown
- Account for 5-6 questions
- Use dummy questions and answers for now

**Comment by mbert015** [comment]
Hello, I need to make the questions have a border (like a table) and not take up all the left and right of the screen :)

**Comment by advilm** [comment]
might want to look into using the [accordion](https://react-bootstrap.github.io/components/accordion/) from react-bootstrap
