### ISSUE TITLE
Change Filter Background to Tailwind

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/acm-atlas#234]
[https://github.com/acm-ucr/acm-hydra/blob/dev/components/Filter.js#L8](https://github.com/acm-ucr/acm-hydra/blob/dev/components/Filter.js#L8)

The filter component was made before we had implemented our custom tailwind colors and hence was not updated to use them, but rather use hex values. Let's change that to use the tailwind colors instead

**Comment by NovaSagittarii** [comment]
got trolled by werid tailwindcss things when trying to do this :^)
