### ISSUE TITLE
Setup Event Click

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/acm-atlas#303]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/36285610/193964134-03aa4d15-c4da-4e97-af14-7962e161043d.png">

- When a user clicks on an event on the calendar, we want to show a modal displaying various information regarding the event
- Create the modal in `Modal.js`

**Comment by NovaSagittarii** [comment]
infinite durability modals be like
