### ISSUE TITLE
Fix Login Button Bug on Mobile

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/acm-atlas#658]
<img width="456" alt="image" src="https://github.com/acm-ucr/acm-hydra/assets/36285610/8e462186-4df7-431c-9ca3-ee39effe1e79">

**Comment by jonbrah** [comment]
What's the bug?

**Comment by jonbrah** [comment]
<img width="372" alt="Screenshot 2023-06-15 at 8 15 45 PM" src="https://github.com/acm-ucr/acm-hydra/assets/92554377/ac754a75-52b5-4597-ada1-4906bdf49a9e">

**Comment by jonbrah** [comment]
Oh is it the uncentered login background?

**Comment by shahdivyank** [comment]
> Oh is it the uncentered login background?

That and then it should be white bg with blue background

**Comment by jonbrah** [comment]
> > Oh is it the uncentered login background?
> 
> That and then it should be white bg with blue background

I don't get it, white background with blue background?

**Comment by shahdivyank** [comment]
> > > Oh is it the uncentered login background?
> > 
> > 
> > That and then it should be white bg with blue background
> 
> I don't get it, white background with blue background?

Padding allows for blue background on the button but mostly white background
