### ISSUE TITLE
Clubroom Info

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/acm-atlas#8]
- Implement Google Map of Clubroom
- Specify room number
- List out features (snacks, whiteboards, tables, microwave, fridge, lockers, etc)

**Comment by lxyna** [comment]
implemented google map, specified room number, haven't listed out features

**Comment by lxyna** [comment]
implemented google map, specified room number, listed out all features written in parentheses but might want to reword/make it sound better
